Add README and remove unrelated tools from original repository
Signed-off-by: Michael Opdenacker <michael.opdenacker@bootlin.com>

diff --git a/bin/fixpdf b/bin/fixpdf
--- a/bin/fixpdf
+++ b/bin/fixpdf
@@ -1,16 +1,14 @@
 #!/bin/sh
 #
-# Usage: odf-replace <document> <string-to-replace> <string-replacement> [xml-file]
-# Tested with OpenOffice.org 3.x and LibreOffice 3.{3,4}
+# Workaround for the Courier font issue found in LibreOffice/OpenOffice 3.3
+# (PDF exported documents had the Courrier font missing, characters being
+# replaced by bullets in Windows).
 #
-# Substitutes all occurrences of a string by another in the given ODF document
+# Fixed in OpenOffice/LibreOffice 3.4
 #
-# xml-file is the part of the document archive the substitution is run on
-# (content.xml by default)
-#
-# Copyright (C) 2010-2012 Bootlin
+# Copyright (C) 2011-2012 Bootlin
 # Author: Michael Opdenacker <michael at bootlin com>
-# Home page: http://git.bootlin.com/training-scripts/
+# Home page: https://github.com/bootlin/odf-tools
 # 
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -33,47 +31,52 @@
 # 675 Mass Ave, Cambridge, MA 02139, USA.
 
 
-DOC=$1
-SOURCE=$2
-REPLACEMENT=$3
-XMLFILE=$4
+. /etc/lsb-release
+PS2PDF=/usr/bin/ps2pdf
+MV='/bin/mv -f'
+RM='/bin/rm -f'
 
-if [ "$XMLFILE" = "" ]
+command_exists () {
+
+        command -v "$1" &> /dev/null
+
+        if [ $? != 0 ]
+        then
+                echo "ERROR: program $1 is not available"
+                exit 1
+        fi
+}
+
+# Fix only needed for Ubuntu before 11.10
+
+compare_version=`echo "$DISTRIB_RELEASE > 11.04" | bc`
+
+if [ $compare_version ]
 then
-	XMLFILE=content.xml
-fi
-
-FILENAME=`basename $DOC`
-TMP=odf-replace.tmp
-NEW=modified.zip
-
-# Extract the document
-
-/bin/rm -rf $TMP
-mkdir -p $TMP
-cp -f $DOC $TMP
-cd $TMP
-/usr/bin/unzip -q $FILENAME
-rm $FILENAME
-
-# Make the substitution
-
-if [ ! -f $XMLFILE ]
-then
-	echo "ERROR: missing $XMLFILE file in document archive. Aborting."
 	exit 1
+
 fi
 
-cat $XMLFILE | sed "s|$SOURCE|$REPLACEMENT|g" > tmpnew.xml
-mv -f tmpnew.xml $XMLFILE
+# Check that all needed commands exist
 
-# Rebuild the archive
+command_exists $PS2PDF
 
-rm -f ../$NEW
-zip --quiet -r ../$NEW .
-cd ..
-mv -f $NEW $DOC
+file=$1
+tmp=${file}-needsfixing.pdf
 
-# Cleanup
+if [ ! -f "$file" ]
+then
+        echo "fixpdf ERROR: the $file document doesn't exist!"
+        exit 1
+fi
 
-/bin/rm -rf $TMP
+$MV -f $file $tmp 
+$PS2PDF $tmp $file
+$RM $tmp
+
+if [ ! -f "$file" ]
+then
+        echo "fixpdf ERROR: ps2pdf failed to fix the $file document"
+        exit 1
+fi
+
